site_name: MachineLearningPipelineV4 Docs
theme:
  name: material
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
nav:
  - Home: 'index'
  - 'Setup':
    - "Installation": "Installation"
  - "About": "About"
